name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install buildozer dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git zip unzip openjdk-17-jdk python3-pip
        pip install cython buildozer

    - name: Init buildozer
      run: buildozer init

    - name: Set up buildozer.spec
      run: |
        sed -i 's/^package.name = .*/package.name = botbacbo/' buildozer.spec
        sed -i 's/^package.domain = .*/package.domain = org.bacbo/' buildozer.spec
        sed -i 's/^requirements =.*/requirements = python3,kivy,sqlite3/' buildozer.spec

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: botbacbo-apk
        path: bin/*.apk
